# Generated by Django 4.1 on 2022-09-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arivage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('source_detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bon_commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bon_commande_nbr', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bon_sortie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bon_sortie_nbr', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email_adress', models.CharField(max_length=100)),
                ('phone_nbr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medic_code', models.CharField(max_length=100)),
                ('medic_name', models.CharField(max_length=100)),
                ('medic_dose', models.CharField(max_length=50)),
                ('dose_unit', models.CharField(max_length=50)),
                ('medic_place', models.CharField(max_length=100)),
                ('medic_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_arrived', models.DateField()),
                ('date_expired', models.DateField()),
                ('stock_qte', models.IntegerField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sortie_qte', models.IntegerField()),
                ('bon_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.bon_sortie')),
                ('med_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Commande_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commande_qte', models.IntegerField()),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.bon_commande')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='bon_sortie',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.source'),
        ),
        migrations.AddField(
            model_name='bon_commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.fournisseur'),
        ),
        migrations.CreateModel(
            name='Arivage_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_expired', models.DateField()),
                ('qnt', models.IntegerField()),
                ('arivage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.arivage')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.medicament')),
            ],
        ),
    ]
